# render.yaml
services:
  - type: web
    name: rdp-bot
    runtime: python
    rootDir: bot
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: NOTIFY_TOKEN
        sync: false
      - key: GITHUB_OWNER
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GH_TOKEN
        sync: false
      - key: TS_TAILNET
        sync: false
      - key: TS_AUTHKEY
        sync: false
      - key: TS_API_KEY
        sync: false
      - key: B2_APPLICATION_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: B2_ENDPOINT
        sync: false
      - key: PORT
        value: "10000"
