name: 🔄 Restart Rapide

on:
  workflow_dispatch:
    inputs:
      ts_authkey:
        description: 'Tailscale Auth Key'
        required: true

jobs:
  run:
    uses: ./.github/workflows/core-engine.yml
    with:
      cycles: "0"
      ts_authkey: ${{ inputs.ts_authkey }}
      mode: "RESTART_DE_SECOURS"
    secrets: inherit
