name: 🟢 Bullet Session A
on:
  workflow_dispatch:
    inputs:
      ts_authkey:
        description: 'Tailscale Auth Key'
        required: true
      cycles:
        description: 'Nombre de cycles'
        required: false
        default: '1'

permissions:
  actions: write
  contents: read

jobs:
  run:
    uses: ./.github/workflows/core-engine.yml
    with:
      cycles: ${{ inputs.cycles }}
      ts_authkey: ${{ inputs.ts_authkey }}
      mode: "SESSION_A"
    secrets: inherit
